---
title: "Plots - Meeting Sept 25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE )

library(leaflet)
library(sf)
library(magrittr)
library(dplyr)

```


```{r}
bip_approved_join <- readRDS("~/git/rural_broadband/data/working/BIP_working/BIP_Approved.RDS") 
bip_tract_786kb <- readRDS("~/git/rural_broadband/data/working/BIP_working/bip_tract_786kb.RDS")

bip_approved_join <- bip_approved_join %>% st_transform(st_crs(bip_tract_786kb))

va_10_tracts <- readRDS("~/git/rural_broadband/data/working/Census Shapefiles/virginia2010censustracts.RDS") %>% st_as_sf()
fcc_10_tracts <- read.csv("~/git/rural_broadband/data/working/FCC_working/fcc2010tract.csv")
va_10_tracts$GEOID10 <- as.numeric(va_10_tracts$GEOID10)
virginia_fcc_coverage <- va_10_tracts %>% left_join(fcc_10_tracts, by = c("GEOID10" = "TRACTID"))
```


### Broadband Initiatives Program

RUS Shapefiles:

* Status - Approved
* Application Status - Approved
* Program Type - contains string "BIP" (includes two programs under BIP: Middle Mile & Last Mile)
* Published - year greater than 2000

NATIONAL MAP 
```{r}
usa_bip_plot <- leaflet() %>% addTiles() %>% addPolygons(data = bip_approved_join, label = bip_approved_join$COMPANY, color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.2,
    fillColor = ~leaflet::colorFactor("YlOrRd", COMPANY)(COMPANY),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))

usa_bip_plot
```

VIRGINIA MAP 
```{r cars}
virginia786 <- leaflet() %>% addTiles() %>% 
  addPolygons(data = bip_tract_786kb, label = bip_tract_786kb$COMPANY, color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~leaflet::colorNumeric("YlOrRd", available786kb)(available786kb),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))

virginia786
```


```{r}
bip_tract_786kb$available786kb <- scales::percent(bip_tract_786kb$available786kb)

available_palette <- colorNumeric(
  palette = "YlOrRd",
  domain = virginia_fcc_coverage$available786kb, n = 5
)

virginia_availabilityplot  <- leaflet() %>% addTiles() %>%
  addPolygons(data = virginia_fcc_coverage, label = virginia_fcc_coverage$available786kb, color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~leaflet::colorNumeric("YlOrRd", available786kb)(available786kb),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE)) %>%
  addLegend("bottomright", pal = available_palette, values = virginia_fcc_coverage$available786kb,
    title = "Available 786 kbps",
    labFormat = labelFormat(suffix = "%"),
    opacity = 1
  ) %>% 
  addPolygons(data = bip_tract_786kb, color = "#FFFFFF", weight = 1, opacity = 1, fillOpacity = 0)

virginia_availabilityplot
```


```{r}
urbanized_areas_VA <- readRDS("~/git/rural_broadband/data/working/urbanized_areas_VA_spjosh.RDS")
places_over20k <- readRDS("~/git/rural_broadband/data/working/placesover20k_VA_spjosh.RDS")

urbanized_areas_VA <- st_as_sf(urbanized_areas_VA)
places_over20k <- st_as_sf(places_over20k)

# virginia_availabilityplot %>% 
#   addPolygons(data = urbanized_areas_VA, color = "#96FA5E", weight = 1, opacity = 1, fillOpacity = 0) %>%
#   addPolygons(data = places_over20k, color = "#96FA5E", weight = 1, opacity = 1, fillOpacity = 0) 


```

```{r}
virginia_fcc_coverage <- virginia_fcc_coverage %>% mutate(eligible786 = ifelse(available786kb <0.26, 1,0))
plot(virginia_fcc_coverage[16])

available_palette <- colorNumeric(
  palette = "YlOrRd",
  domain = virginia_fcc_coverage$eligible786, n = 2
)

virginia_availabilityplot  <- leaflet() %>% addTiles() %>%
  addPolygons(data = virginia_fcc_coverage, label = virginia_fcc_coverage$eligible786, color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~leaflet::colorNumeric("YlOrRd", eligible786)(eligible786),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE)) %>%
  addLegend("bottomright", pal = available_palette, values = virginia_fcc_coverage$eligible786,
    title = "Available 786 kbps",
    labFormat = labelFormat(suffix = "%"),
    opacity = 1
  ) %>% 
  addPolygons(data = bip_tract_786kb, color = "#FFFFFF", weight = 1, opacity = 1, fillOpacity = 0)

virginia_availabilityplot


```



```{r, eval = FALSE}
states <- sf::st_as_sf(rgdal::readOGR(dsn="~/git/rural_broadband/data/census_geo_cb/",layer="cb_2017_us_state_20m"))
state_va <- states %>% filter(STUSPS == "VA")

# urbanized_areas_VA %>% st_join(state_va) %>% plot()
# places_over20k %>% st_join(state_va) %>% plot()

# st_intersection(urbanized_areas_VA, places_over20k) %>% nrow()
# nrow(urbanized_areas_VA)
# nrow(places_over20k)
# plot(test[4])
# plot(urbanized_areas_VA[4])
# plot(places_over20k[4])

ineligible_pop <- st_union(urbanized_areas_VA, places_over20k) 
ineligible_pop <- state_va %>% st_intersection(ineligible_pop) 
plot(ineligible_pop[26])
ineligible_pop

ineligible_pop_single <- st_combine(ineligible_pop)
plot(ineligible_pop_single)

```


```{r, eval = FALSE}
leaflet() %>% addTiles() %>%
  addPolygons(data = ineligible_pop)

#, color = "#FFFFFF", weight = 0, opacity = 1, fillOpacity = 0.5)
```


























