---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
```



```{r 2014_FINAL_ELIGIBILITY_DATA}
# final 2014 eligibility with area
# USA_speed_rural_criteria_2014_censusblocks <- readRDS("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/working/eligibility_summary_percentages//USA_2014_FULLCRITERIA_final_criteria_eligibility_wArea_21OCT2020.RDS")

savepath <- "/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/working/eligibility_summary_percentages/"

# ReConnect 2014 - BLOCK CT
rc_14_state_BC <- readRDS(paste0(savepath, "2014_state_summary_block_ct_perc_elig", "_OCT21_2020", ".RDS"))
rc_14_county_BC <- readRDS(paste0(savepath, "2014_county_summary_blockct_perc_elig", "_OCT21_2020", ".RDS"))
rc_14_tract_BC <- readRDS(paste0(savepath, "2014_tract_summary_blockct_perc_elig", "_OCT21_2020", ".RDS"))

# ReConnect 2014 - AREA
rc_14_state_AREA <- readRDS(paste0(savepath, "2014_state_summary_area_perc_elig", "_OCT21_2020", ".RDS"))
rc_14_county_AREA <- readRDS(paste0(savepath, "2014_county_summary_area_perc_elig", "_OCT21_2020", ".RDS"))
rc_14_tract_AREA <- readRDS(paste0(savepath, "2014_tract_summary_area_perc_elig", "_OCT21_2020", ".RDS"))

# Community Connect 2014 - BLOCK CT
cc_14_state_BC <- readRDS(paste0(savepath, "2014_state_summary_cc_block_ct_perc_elig", "_OCT20_2020", ".RDS"))
cc_14_county_BC <- readRDS(paste0(savepath, "2014_county_summary_cc_blockct_perc_elig", "_OCT20_2020", ".RDS"))
cc_14_tract_BC <- readRDS(paste0(savepath, "2014_tract_summary_cc_blockct_perc_elig", "_OCT20_2020", ".RDS"))

# Community Connect 2014 - AREA
cc_14_state_AREA <- readRDS(paste0(savepath, "2014_state_summary_cc_area_perc_elig", "_OCT21_2020", ".RDS"))
cc_14_county_AREA <- readRDS(paste0(savepath, "2014_county_summary_cc_area_perc_elig", "_OCT21_2020", ".RDS"))
cc_14_tract_AREA <- readRDS(paste0(savepath, "2014_tract_summary_cc_area_perc_elig", "_OCT21_2020", ".RDS"))
```


```{r 2018_ELIGIBILITY_FINAL_DATA}
# final 2018 eligibility with area, without missing/duplicated states
# USA_speed_rural_criteria_2018_censusblocks <- readRDS("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/working/eligibility_summary_percentages//USA_2018_FULLCRITERIA_final_criteria_eligibility_wArea_21OCT2020.RDS")

savepath <- "/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/working/eligibility_summary_percentages/"

# ReConnect 2018 - BLOCK CT
rc_18_state_BC <- readRDS(paste0(savepath, "2018_state_summary_block_ct_perc_elig", "_OCT21_2020", ".RDS"))
rc_18_county_BC <- readRDS(paste0(savepath, "2018_county_summary_blockct_perc_elig", "_OCT21_2020", ".RDS"))
rc_18_tract_BC <- readRDS(paste0(savepath, "2018_tract_summary_blockct_perc_elig", "_OCT21_2020", ".RDS"))

# ReConnect 2018 - AREA
rc_18_state_AREA <- readRDS(paste0(savepath, "2018_state_summary_area_perc_elig", "_OCT21_2020", ".RDS"))
rc_18_county_AREA <- readRDS(paste0(savepath, "2018_county_summary_area_perc_elig", "_OCT21_2020", ".RDS"))
rc_18_tract_AREA <- readRDS(paste0(savepath, "2018_tract_summary_area_perc_elig", "_OCT21_2020", ".RDS"))

# Community Connect 2018 - BLOCK CT
cc_18_state_BC <- readRDS(paste0(savepath, "2018_state_summary_cc_block_ct_perc_elig", "_OCT21_2020", ".RDS"))
cc_18_county_BC <- readRDS(paste0(savepath, "2018_county_summary_cc_blockct_perc_elig", "_OCT21_2020", ".RDS"))
cc_18_tract_BC <- readRDS(paste0(savepath, "2018_tract_summary_cc_blockct_perc_elig", "_OCT21_2020", ".RDS"))

# Community Connect 2018 - AREA
cc_18_state_AREA <- readRDS(paste0(savepath, "2018_state_summary_cc_area_perc_elig", "_OCT21_2020", ".RDS"))
cc_18_county_AREA <- readRDS(paste0(savepath, "2018_county_summary_cc_area_perc_elig", "_OCT21_2020", ".RDS"))
cc_18_tract_AREA <- readRDS(paste0(savepath, "2018_tract_summary_cc_area_perc_elig", "_OCT21_2020", ".RDS"))
```

```{r}
fips  <- tigris::fips_codes 
fips_ <- fips %>% select(state, state_code) %>% distinct()
```

## SUMMARY - NATIONAL

```{r}
sum(rc_14_state_BC$Total)
sum(cc_14_state_BC$Total)

sum(rc_18_state_BC$Total)
sum(cc_18_state_BC$Total)

rc_14_state_BC 
```

```{r}
non_states <- c("DC", "AS", "GU", "MP")
```


## SUMMARY - STATES

```{r}
state_eligibilities <- rbind(rc_14_state_BC  %>% select(1, 5) %>% mutate(Year = "2014", Program = "RC", Elig = "BC"), 
rc_14_state_AREA %>% select(1, 5) %>% mutate(Year = "2014", Program = "RC", Elig = "AREA"), 
cc_14_state_BC %>% select(1, 5) %>% mutate(Year = "2014", Program = "CC", Elig = "BC"), 
cc_14_state_AREA %>% select(1, 5) %>% mutate(Year = "2014", Program = "CC", Elig = "AREA"), 
rc_18_state_BC  %>% select(1, 5) %>% mutate(Year = "2018", Program = "RC", Elig = "BC"),
rc_18_state_AREA  %>% select(1, 5) %>% mutate(Year = "2018", Program = "RC", Elig = "AREA"), 
cc_18_state_BC  %>% select(1, 5) %>% mutate(Year = "2018", Program = "CC", Elig = "BC"), 
cc_18_state_AREA  %>% select(1, 5) %>% mutate(Year = "2018", Program = "CC", Elig = "AREA"))

state_eligibilities <- state_eligibilities %>% left_join(fips_, by = c("STATEFP10" = "state_code"))

state_perc_diff_time <- state_eligibilities %>% 
  reshape2::dcast(STATEFP10 + state + Program + Elig ~ Year, value.var = "PERC_ELIGIBLE") %>%
  mutate(PERC_CHANGE = `2018` - `2014`) %>%
  select(-`2014`, -`2018`)

state_eligibilities <- state_eligibilities %>% 
  left_join(state_perc_diff_time, by = c("STATEFP10", "state", "Program", "Elig")) %>%
  mutate(PERC_CHANGE = round(PERC_CHANGE, digits = 2))

```


```{r}
(table(USA_speed_rural_criteria_2014_censusblocks$disqualification3) )
(table(USA_speed_rural_criteria_2018_censusblocks$disqualification3) )
```


```{r}
rc_bc_perc_change <- state_eligibilities %>% filter(Year == "2018", Program == "RC" & Elig == "BC") %>% mutate(non_state = state %in% non_states)

ggplot(data = rc_bc_perc_change, mapping = aes(x = reorder(state, PERC_CHANGE), y = PERC_CHANGE, fill = non_state)) + 
  geom_bar(stat = "identity") +
  labs(title = "ReConnect - Change in Percent Eligibility - USA") + 
  xlab(label = "States") + 
  ylab(label = "Change in Percent Eligibility ")

cc_bc_perc_change <- state_eligibilities %>% filter(Year == "2018", Program == "CC" & Elig == "BC") %>% mutate(non_state = state %in% non_states)

ggplot(data = cc_bc_perc_change, mapping = aes(x = reorder(state, PERC_CHANGE), y = PERC_CHANGE, fill = non_state)) + 
  geom_bar(stat = "identity") +
  labs(title = "Community Connect - Change in Percent Eligibility - USA") + 
  xlab(label = "States") + 
  ylab(label = "Change in Percent Eligibility ")

bc_perc_change <- state_eligibilities %>% filter(Year == "2018" & Elig == "BC") %>% mutate(non_state = state %in% non_states)

ggplot(data = bc_perc_change, mapping = aes(x = reorder(state, PERC_CHANGE), y = PERC_CHANGE, fill = non_state)) + 
  geom_bar(stat = "identity", position = "identity") +
  facet_wrap(~Program, ncol = 1) + 
  labs(title = "Community Connect - Change in Percent Eligibility - USA") + 
  xlab(label = "States") + 
  ylab(label = "Change in Percent Eligibility ")
```



```{r}
ggplot(state_eligibilities %>% filter(Elig == "BC"), aes(x = reorder(state, -PERC_ELIGIBLE), y = PERC_ELIGIBLE, fill = Year)) + 
  geom_bar(stat = "identity", position = "identity") + 
  geom_text(data = state_eligibilities %>% filter(Year == "2018" & Elig == "BC"), stat = "identity", aes(label = reorder(PERC_CHANGE, -PERC_ELIGIBLE), hjust=0.5, vjust = -1)) +
  facet_wrap(~Program, ncol = 1) + 
  labs(title = "Percent Eligibility - States") + 
  xlab(label = "States") + 
  ylab(label = "Percent Eligibility (% by block count)") + 
  theme(legend.position = 'bottom')

# ggplot(state_eligibilities %>% filter(Elig == "BC" & state %in% non_states == FALSE), aes(x = reorder(state, -PERC_ELIGIBLE), y = PERC_ELIGIBLE, fill = Year)) + 
#   geom_bar(stat = "identity", position = "identity") + 
#   geom_text(data = state_eligibilities %>% filter(Year == "2018" & Elig == "BC" & state %in% non_states == FALSE), stat = "identity", aes(label = reorder(PERC_CHANGE, -PERC_ELIGIBLE), hjust=0.5, vjust = -1)) +
#   facet_wrap(~Program, ncol = 1) + 
#   labs(title = "Percent Eligibility - States") + 
#   xlab(label = "States") + 
#   ylab(label = "Percent Eligibility (% by block count)") + 
#   theme(legend.position = 'bottom')
```


### Virginia

```{r}
va <- state_eligibilities %>% filter(state == "VA")

state_perc_diff_time <- state_eligibilities %>% 
  reshape2::dcast(STATEFP10 + state + Program + Elig ~ Year, value.var = "PERC_ELIGIBLE") %>%
  mutate(PERC_CHANGE = `2018` - `2014`) %>%
  select(-`2014`, -`2018`)

va <- va %>% 
  left_join(state_perc_diff_time, by = c("STATEFP10", "state", "Program", "Elig")) %>%
  mutate(PERC_CHANGE = round(PERC_CHANGE, digits = 2))
```


```{r}
ggplot(va, aes(x = Program, y = PERC_ELIGIBLE, fill = Year)) + 
  geom_bar(stat = "identity", position = "identity") + 
  geom_text(data = va %>% filter(Year == "2018"), stat = "identity", aes(label = reorder(PERC_CHANGE, -PERC_ELIGIBLE), hjust=0.5, vjust = -1)) + 
  facet_wrap(~Elig) + 
  labs(title = "Percent Eligibility - State") + 
  xlab(label = "Virginia") + 
  ylab(label = "Percent Eligibility ")

```


```{r}

highlights <- c("IN", "VA") # 18, 51
fips_ %>% filter(state %in% highlights)

va_cc_14_county_BC <- cc_14_county_BC %>% filter(STATEFP10 == "51")
va_rc_14_county_BC <- rc_14_county_BC %>% filter(STATEFP10 == "51")
va_cc_18_county_BC <- cc_18_county_BC %>% filter(STATEFP10 == "51")
va_rc_18_county_BC <- rc_18_county_BC %>% filter(STATEFP10 == "51")

va_14 <- rbind(va_cc_14_county_BC %>% mutate(PROG = "CC"), va_rc_14_county_BC %>% mutate(PROG = "RC")) 

ggplot(data = va_14, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

va_18 <- rbind(va_cc_18_county_BC %>% mutate(PROG = "CC"), va_rc_18_county_BC %>% mutate(PROG = "RC")) 

ggplot(data = va_18, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)


va_cc_14_county_AREA <- cc_14_county_AREA %>% filter(STATEFP10 == "51")
va_rc_14_county_AREA <- rc_14_county_AREA %>% filter(STATEFP10 == "51")
va_cc_18_county_AREA <- cc_18_county_AREA %>% filter(STATEFP10 == "51")
va_rc_18_county_AREA <- rc_18_county_AREA %>% filter(STATEFP10 == "51")

va_14_ <- rbind(va_cc_14_county_AREA %>% mutate(PROG = "CC"), va_rc_14_county_AREA %>% mutate(PROG = "RC")) 

ggplot(data = va_14_, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

va_18_ <- rbind(va_cc_18_county_AREA %>% mutate(PROG = "CC"), va_rc_18_county_AREA %>% mutate(PROG = "RC")) 

ggplot(data = va_18_, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

va_single_axis <- rbind(rbind(va_cc_14_county_BC %>% mutate(PROG = "CC"), va_rc_14_county_BC %>% mutate(PROG = "RC")) %>% mutate(Year = "2014"),
rbind(va_cc_18_county_BC %>% mutate(PROG = "CC"), va_rc_18_county_BC %>% mutate(PROG = "RC")) %>% mutate(Year = "2018"))

ggplot(data = va_single_axis, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG+Year)
```

```{r}
va_counties <- tigris::counties(state = "51")

va_counties <- va_counties %>% left_join(va_14 %>% filter(PROG == "CC") %>% select(STATEFP10, COUNTYFP10, PERC_ELIGIBLE), by = c("STATEFP" = "STATEFP10", "COUNTYFP" = "COUNTYFP10"))

# va_14 %>% filter(PROG == "CC") %>% select(STATEFP10, COUNTYFP10, PERC_ELIGIBLE) %>% filter(COUNTYFP10 == "775")

leaflet(va_counties) %>% 
  addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5, fillColor = ~colorQuantile("YlOrRd", PERC_ELIGIBLE)(PERC_ELIGIBLE))
```

```{r}
va_counties %>% as.data.frame() %>% select(NAMELSAD, PERC_ELIGIBLE) %>% arrange(NAMELSAD)
```

### Indiana

```{r}
in_ <- state_eligibilities %>% filter(state == "IN")

in_ <- in_ %>% 
  left_join(state_perc_diff_time, by = c("STATEFP10", "state", "Program", "Elig")) %>%
  mutate(PERC_CHANGE = round(PERC_CHANGE.x, digits = 2))
```


```{r}
ggplot(in_, aes(x = Program, y = PERC_ELIGIBLE, fill = Year)) + 
  geom_bar(stat = "identity", position = "identity") + 
  geom_text(data = in_ %>% filter(Year == "2018"), stat = "identity", aes(label = reorder(PERC_CHANGE, -PERC_ELIGIBLE), hjust=0.5, vjust = -1)) + 
  facet_wrap(~Elig) + 
  labs(title = "Percent Eligibility - State") + 
  xlab(label = "Indiana") + 
  ylab(label = "Percent Eligibility ")

```


```{r}
in_cc_14_county_BC <- cc_14_county_BC %>% filter(STATEFP10 == "18")
in_rc_14_county_BC <- rc_14_county_BC %>% filter(STATEFP10 == "18")
in_cc_18_county_BC <- cc_18_county_BC %>% filter(STATEFP10 == "18")
in_rc_18_county_BC <- rc_18_county_BC %>% filter(STATEFP10 == "18")

in_14 <- rbind(in_cc_14_county_BC %>% mutate(PROG = "CC"), in_rc_14_county_BC %>% mutate(PROG = "RC")) 

ggplot(data = in_14, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

in_18 <- rbind(in_cc_18_county_BC %>% mutate(PROG = "CC"), in_rc_18_county_BC %>% mutate(PROG = "RC")) 

ggplot(data = in_18, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)


in_cc_14_county_AREA <- cc_14_county_AREA %>% filter(STATEFP10 == "18")
in_rc_14_county_AREA <- rc_14_county_AREA %>% filter(STATEFP10 == "18")
in_cc_18_county_AREA <- cc_18_county_AREA %>% filter(STATEFP10 == "18")
in_rc_18_county_AREA <- rc_18_county_AREA %>% filter(STATEFP10 == "18")

in_14_ <- rbind(in_cc_14_county_AREA %>% mutate(PROG = "CC"), in_rc_14_county_AREA %>% mutate(PROG = "RC")) 

ggplot(data = in_14_, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

in_18_ <- rbind(in_cc_18_county_AREA %>% mutate(PROG = "CC"), in_rc_18_county_AREA %>% mutate(PROG = "RC")) 

ggplot(data = in_18_, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

in_single_axis <- rbind(rbind(in_cc_14_county_BC %>% mutate(PROG = "CC"), in_rc_14_county_BC %>% mutate(PROG = "RC")) %>% mutate(Year = "2014"), rbind(in_cc_18_county_BC %>% mutate(PROG = "CC"), in_rc_18_county_BC %>% mutate(PROG = "RC")) %>% mutate(Year = "2018"))

ggplot(data = in_single_axis, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG+Year)
```

```{r}
in_counties <- tigris::counties(state = "18")

in_counties <- in_counties %>% left_join(in_14 %>% filter(PROG == "CC") %>% select(STATEFP10, COUNTYFP10, PERC_ELIGIBLE), by = c("STATEFP" = "STATEFP10", "COUNTYFP" = "COUNTYFP10"))

# va_14 %>% filter(PROG == "CC") %>% select(STATEFP10, COUNTYFP10, PERC_ELIGIBLE) %>% filter(COUNTYFP10 == "775")

leaflet(in_counties) %>% 
  addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5, fillColor = ~colorQuantile("YlOrRd", PERC_ELIGIBLE)(PERC_ELIGIBLE))
```

```{r}
in_counties %>% as.data.frame() %>% select(NAMELSAD, PERC_ELIGIBLE) %>% arrange(NAMELSAD)
```

### Washington

```{r}
wa <- state_eligibilities %>% filter(state == "WA")

wa <- wa %>% 
  left_join(state_perc_diff_time, by = c("STATEFP10", "state", "Program", "Elig")) %>%
  mutate(PERC_CHANGE = round(PERC_CHANGE.x, digits = 2))
```


```{r}
ggplot(wa, aes(x = Program, y = PERC_ELIGIBLE, fill = Year)) + 
  geom_bar(stat = "identity", position = "identity") + 
  geom_text(data = wa %>% filter(Year == "2018"), stat = "identity", aes(label = reorder(PERC_CHANGE, -PERC_ELIGIBLE), hjust=0.5, vjust = -1)) + 
  facet_wrap(~Elig) + 
  labs(title = "Percent Eligibility - State") + 
  xlab(label = "Washington") + 
  ylab(label = "Percent Eligibility ")

```

```{r}
fips_ %>% filter(state == "WA")
```


```{r}


wa_cc_14_county_BC <- cc_14_county_BC %>% filter(STATEFP10 == "53")
wa_rc_14_county_BC <- rc_14_county_BC %>% filter(STATEFP10 == "53")
wa_cc_18_county_BC <- cc_18_county_BC %>% filter(STATEFP10 == "53")
wa_rc_18_county_BC <- rc_18_county_BC %>% filter(STATEFP10 == "53")

wa_14 <- rbind(wa_cc_14_county_BC %>% mutate(PROG = "CC"), wa_rc_14_county_BC %>% mutate(PROG = "RC")) 

ggplot(data = wa_14, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

wa_18 <- rbind(wa_cc_18_county_BC %>% mutate(PROG = "CC"), wa_rc_18_county_BC %>% mutate(PROG = "RC")) 

ggplot(data = wa_18, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)


wa_cc_14_county_AREA <- cc_14_county_AREA %>% filter(STATEFP10 == "53")
wa_rc_14_county_AREA <- rc_14_county_AREA %>% filter(STATEFP10 == "53")
wa_cc_18_county_AREA <- cc_18_county_AREA %>% filter(STATEFP10 == "53")
wa_rc_18_county_AREA <- rc_18_county_AREA %>% filter(STATEFP10 == "53")

wa_14_ <- rbind(wa_cc_14_county_AREA %>% mutate(PROG = "CC"), wa_rc_14_county_AREA %>% mutate(PROG = "RC")) 

ggplot(data = wa_14_, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

wa_18_ <- rbind(wa_cc_18_county_AREA %>% mutate(PROG = "CC"), wa_rc_18_county_AREA %>% mutate(PROG = "RC")) 

ggplot(data = wa_18_, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG, ncol = 1)

wa_single_axis <- rbind(rbind(wa_cc_14_county_BC %>% mutate(PROG = "CC"), wa_rc_14_county_BC %>% mutate(PROG = "RC")) %>% mutate(Year = "2014"), rbind(wa_cc_18_county_BC %>% mutate(PROG = "CC"), wa_rc_18_county_BC %>% mutate(PROG = "RC")) %>% mutate(Year = "2018"))

ggplot(data = wa_single_axis, aes(x = PERC_ELIGIBLE)) +
  geom_histogram() + 
  facet_wrap(~PROG+Year)
```

```{r}
wa_counties <- tigris::counties(state = "53")

wa_counties_14 <- wa_counties %>% left_join(wa_14 %>% filter(PROG == "CC") %>% select(STATEFP10, COUNTYFP10, PERC_ELIGIBLE), by = c("STATEFP" = "STATEFP10", "COUNTYFP" = "COUNTYFP10"))

leaflet(wa_counties_14) %>% 
  addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5, fillColor = ~colorBin("YlOrRd", PERC_ELIGIBLE)(PERC_ELIGIBLE))

wa_counties_18 <- wa_counties %>% left_join(wa_18 %>% filter(PROG == "CC") %>% select(STATEFP10, COUNTYFP10, PERC_ELIGIBLE), by = c("STATEFP" = "STATEFP10", "COUNTYFP" = "COUNTYFP10"))

leaflet(wa_counties_18) %>% 
  addTiles() %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5, fillColor = ~colorBin("YlOrRd", PERC_ELIGIBLE)(PERC_ELIGIBLE))
```

```{r}
wa_counties %>% as.data.frame() %>% select(NAMELSAD, PERC_ELIGIBLE) %>% arrange(NAMELSAD)
```


#################


```{r}
library(ggplot2)
library(maps)
library(dplyr)

MainStates <- map_data("state")

ggplot() + 
  geom_polygon( data= MainStates, aes(x=long, y=lat, group=group),
                color="black", fill="lightblue" )
```


```{r}
state_eligibilities %>% filter(state == "VA")
```



```{r}
ggplot(state_eligibilities %>% filter(Elig == "AREA"), aes(x = reorder(state, -PERC_ELIGIBLE), y = PERC_ELIGIBLE, fill = Year)) + 
  geom_bar(stat = "identity", position = "identity") + 
  geom_text(data = state_eligibilities %>% filter(Year == "2018" & Elig == "AREA"), stat = "identity", aes(label = reorder(PERC_CHANGE, -PERC_ELIGIBLE), hjust=0.5, vjust = -1)) +
  facet_wrap(~Program, ncol = 1) + 
  labs(title = "Percent Eligibility - States") + 
  xlab(label = "States") + 
  ylab(label = "Percent Eligibility (% by area)")

```


```{r}
state_eligibilities %>% filter(state == "GU")
```

```{r}
state_eligibilities %>% filter(state == "WA")
```



```{r}

WA_2014_ <- WA_2014 %>% as.data.frame() %>% count(disqualification3)
WA_2018_ <- WA_2018 %>% as.data.frame() %>% count(disqualification3)

WA_2014_ <- WA_2014_ %>% mutate(year = 2014,
                    RC_ELIG = ifelse(disqualification3 == "not disqual by speed/rural", 1, 0), 
                    CC_ELIG = ifelse(disqualification3 %in% c("not disqual by speed/rural", "caf2 only", "prot borr only", "prot borr only + caf2"), 1, 0))

WA_2018_ <- WA_2018_ %>% mutate(year = 2018,
                    RC_ELIG = ifelse(disqualification3 == "not disqual by speed/rural", 1, 0), 
                    CC_ELIG = ifelse(disqualification3 %in% c("not disqual by speed/rural", "caf2 only", "prot borr only", "prot borr only + caf2"), 1, 0))

rbind(WA_2014_ %>% group_by(year, RC_ELIG, CC_ELIG) %>% summarise(sum = sum(n)), WA_2018_ %>% group_by(year, RC_ELIG, CC_ELIG) %>% summarise(sum = sum(n))) #%>% reshape2::dcast(RC_ELIG + CC_ELIG ~ year, value.var = "sum") %>% mutate(diff = `2018`-`2014`)

# ReConnect - 
# eligible / total
18378/(170976 + 6220 + 18378) # RC 2014 - 9%
25447/(161982 + 8145 + 25447)  # RC 2018 - 13%
(18378 + 6220)/(170976 + 6220 + 18378) # CC 2014 - 12%
(8145 + 25447)/(161982 + 8145 + 25447) # CC 2018 - 17%


WA_2014_ %>% filter(CC_ELIG == 0)
WA_2018_ %>% filter(CC_ELIG == 0)

change_reasons <- rbind(WA_2014_ %>% select(year, disqualification3, CC_ELIG, n), WA_2018_ %>% select(year, disqualification3, CC_ELIG, n)) %>% 
  reshape2::dcast(disqualification3 + CC_ELIG ~ year, value.var = "n") %>% 
  mutate(diff_source = `2018` - `2014`) %>% 
  filter(abs(diff_source) > 20) %>% 
  mutate(change_reason = recode_factor(disqualification3, 
                                       `caf2 only` = "Projects", 
                                       `not disqual by speed/rural` = "Ignore",
                                       `prot borr only` = "Projects", 
                                       `rural only` = "Rural",
                                       `rural only + caf2` = "Rural",
                                       `rural only, not in fcc` = "Rural",
                                       `rural only, not in fcc + caf2` = "Rural",
                                       `speed only` = "Speed",
                                       `speed + prot borr` = "Speed",
                                       `speed only + caf2` = "Speed"
                                       ))

change_reasons %>% group_by(change_reason) %>% summarise(net_change = sum(diff_source))

```



