---
title: "Eligibility - Rurality (Census) x Service (FCC)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(sf)

# setwd("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/")

```

```{r download_save_data, eval = FALSE}
urbanareas2017 <- tigris::urban_areas(year = "2017")
fips  <- tigris::fips_codes 
fips %>% filter(state_code == 74)

rm(i)
for (i in 57:nrow(fips_codes)) {
  print(i)
  # print(fips_codes[i,1])
  print(fips_codes[i,2])
  censusplaces2017_ <- tigris::places(state = fips_codes[i,1], year = "2017")
  name <- paste0("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/census_2017_urbanareas_places/census_2017_places_", fips_codes[i,1], ".RDS")
  saveRDS(censusplaces2017_, file = name)
  print(name)
}

# saveRDS(censusplaces2017_, paste0("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/census_2017_urbanareas_places/census_2017_places_", fips_codes[1,1], ".RDS"))

# saveRDS(urbanareas2017, "/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/census_2017_urbanareas.RDS")

```

Note: FCC Data is from https://www.fcc.gov/form-477-broadband-deployment-data-december-2017-version-2
Pulled: US - Fixed without Satellite - Dec 17v2 (CSV)

Rurality files - 2017 urban areas and census designated places


```{r}
## FCC
# fcc_2017 <- read.csv("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/fbd_us_without_satellite_dec2017_v2.csv")
# saveRDS(fcc_2017, "/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/fbd_us_without_satellite_dec2017_v2.RDS")
fcc_2017 <- readRDS("/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/fcc_availability/fbd_us_without_satellite_dec2017_v2.RDS")

## RURALITY 
path <- "/project/biocomplexity/sdad/projects_data/project_data/usda/rural_broadband/census_2017_urbanareas_places/"
rurality_files <- list.files(path)
urbanareas2017 <- readRDS(paste0(path, rurality_files[57]))
rurality_files <- rurality_files[1:56]
rurality_files <- paste0(path, rurality_files)
data_l <- as.list(rurality_files)
shps <- lapply(data_l, function(x) readRDS(x))
shps_e <- do.call(rbind, shps)

## CENSUS

### clean environment
rm(rurality_files, urbanareas2017, data_l, shps)
```


```{r}
fcc_2017 <- fcc_2017  %>% mutate(speed_elig_down = ifelse(MaxAdDown > 10, 0, 1),
                                  speed_elig_up = ifelse(MaxAdUp > 1, 0, 1),
                                  speed_elig = ifelse(speed_elig_down + speed_elig_up == 2, 1, 0))
fips  <- tigris::fips_codes 
fips_ <- fips %>% select(state, state_code) %>% distinct()

fcc_2017_VA <- fcc_2017 %>% filter(StateAbbr == "VA")

va_blocks_2018 <- readRDS("/project/biocomplexity/sdad/projects_data/usda/bb/original/censusblocks/blocks_TIGER2018_sf_RDS/tl_2018_51_tabblock10.RDS")
va_blocks_2018 <- va_blocks_2018 %>% mutate(FULL_GEOID = paste0(STATEFP10, COUNTYFP10, TRACTCE10, BLOCKCE10))
fcc_2017_VA$BlockCode <- as.character(fcc_2017_VA$BlockCode)

fcc_2017_VA <- va_blocks_2018 %>% inner_join(fcc_2017_VA, by = c("FULL_GEOID" = "BlockCode")) 
# test_fcc <- fcc_2017_VA %>% filter(speed_elig == 2)
# plot(test_fcc$geometry)

# plot_elig <- fcc_2017_VA %>% filter(speed_elig == 1)
# plot_elig <- plot_elig %>% st_transform(st_crs(4326))



```

```{r}
rurality_va <- shps_e %>% filter(STATEFP == "51")
plot(rurality_va$geometry)

library(leaflet)

leaflet(rurality_va) %>% 
  addTiles() %>%
  addPolygons(stroke = 0, fillOpacity = .5, color = "#32a852") 

```


```{r}
test_va_fcc <- fcc_2017_VA %>% filter(stringr::str_detect(TRACTCE10, "430"))

test_intersection <- st_intersection(test_va_fcc, rurality_va)  %>% 
  mutate(geo =st_geometry_type(geometry)) %>% 
  filter(stringr::str_detect(geo, "POLYG"))

leaflet(test_intersection) %>%
  addTiles() %>% 
  addPolygons()
```






